[tools]
"aqua:godotengine/godot" = "latest"
pre-commit = "latest"
"ubi:DonIsaac/zlint" = "latest"
usage = "latest"
zig = "0.15.1"
zls = "0.15.0"

[tasks."example:build"]
dir = "example"
run = "zig build"

[tasks."example:run"]
dir = "example/project"
run = "godot"

[tasks."docs:build"]
run = "zig build docs"

[tasks."docs:serve"]
dir = "zig-out/docs"
depends = ["docs:build"]
run = "mise exec bun -- bunx -y node-static ."
