[tools]
pre-commit = "latest"
"ubi:DonIsaac/zlint" = "latest"
usage = "latest"
zig = "0.15.1"
zls = "0.15.0"

[tasks."example:build"]
dir = "example"
run = "zig build"

[tasks."example:run"]
dir = "example"
run = "zig build run"
